# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "文章"
  pageRef = "posts"  #引用 contents/posts 目录, 显示 list
  weight = 10

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 11

[[main]]
  name = "参考手册"
  pageRef = "manuals"
  weight = 12

[[main]]
  name = "Rust 语言 - 个人参考手册"
  parent = "参考手册"
  pageRef = "rust/rust-lang"
  weight = 13

[[main]]
  name = "C 语言 - 个人参考手册"
  parent = "参考手册"
  pageRef = "c"
  weight = 14

[[main]]
  name = "C预处理器 - 个人参考手册"
  parent = "参考手册"
  pageRef = "cpp"
  weight = 15

[[main]]
  name = "Makefile - 个人参考手册"
  parent = "参考手册"
  pageRef = "makefile"
  weight = 16

[[main]]
  name = "Emacs - 个人参考手册"
  parent = "参考手册"
  pageRef = "emacs/my-emacs-ref"
  weight = 17
  
# [[subnavigation]]
#    name = "An interesting topic"
#    pageRef = "tags/interesting-topic"
#    weight = 10

# [[subnavigation]]
#    name = "My Awesome Category"
#    pre = "github"
#    pageRef = "categories/awesome"
#    weight = 20

# [[main]]
#   name = "标签"
#   pageRef = "tags"
#   weight = 30

# [[main]]
#    name = "eBPF"
#    pageRef = "ebpf"
#    weight = 20

# [[main]]
#    name = "Shell"
#    pageRef = "shell"
#    weight = 20

# [[main]]
#    name = "K8S"
#    pageRef = "k8s"
#    weight = 20

# [[main]]
#    name = "Emacs"
#    pageRef = "emacs"
#    weight = 20

# [[main]]
#    name = "Books"
#    pageRef = "book"
#    weight = 20

[[main]]
  identifier = "twitter"
  pre = "twitter"
  url = "https://twitter.com/geekard_zj"
  weight = 1000 # 从较大的数字开始，确保是在所有已知目录链接的右边。

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/opsnull"
  weight = 2000

# [[footer]]
#   name = "分类"
#   pageRef = "categories"
#   weight = 2
